instance_create(x,y,obj_particle)
instance_create(x,y,obj_particle)
instance_create(x,y,obj_particle)
instance_create(x,y,obj_particle)
instance_create(x,y,obj_particle)
instance_create(x,y,obj_particle)
instance_create(x,y,obj_particle)
instance_create(x,y,obj_particle)
